algoritmo "MeuPrimeiroAlgoritmo"

var
// seção de declaração de variaveis
nome:caracter
idade:inteiro
altura:real
casado:logico

inicio
// seção de comandos
//nome <- "Léia"
//idade <- 36
//altura <- 1.59
//casado <- falso

escreval("Digite seu nome")
leia(nome)
escreval("Digite sua idade")
leia(idade)
escreval("Digite sua altura")
leia(altura)
escreva("Seu nome é ", nome , "Sua idade é ", idade , " sua altura é " , altura)

fimalgoritmo
